
trigger:
- main

variables:
  - group: CI_Var
  - name: releaseNumber
    value: $(major).$(minor).$(Rev:r)

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '2c3749dd-45ac-4bc0-b897-9e4d58e3a6fa'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
     git tag $(releaseNumber)
     git push origin $(releaseNumber)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Git Tag

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ReleasiServiceConnection_chechoXR'
    repositoryName: 'chechoXR/PrecannonWarn'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(releaseNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'