
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '2c3749dd-45ac-4bc0-b897-9e4d58e3a6fa'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ReleasiServiceConnection_chechoXR'
    repositoryName: 'chechoXR/PrecannonWarn'
    action: 'create'
    target: '$(myCommitSHA)'
    tagSource: 'gitTag'
    tagPattern: '$(Build.SourceVersion)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'