
trigger:
- main

name: $(major).$(minor).$(Rev:r)

variables:
  - group: CI_Var
  - name: Version
    value: $(Build.BuildNumber)


pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true

- task: DotNetCoreCLI@2
  displayName: Restore app dependencies
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '2c3749dd-45ac-4bc0-b897-9e4d58e3a6fa'

- task: DotNetCoreCLI@2
  displayName: Build app
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
     git tag $(Build.BuildNumber)
     git push origin $(Build.BuildNumber)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Git Tag
 
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ReleasiServiceConnection_chechoXR'
    repositoryName: 'chechoXR/PrecannonWarn'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: 'PrecannonWarn $(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Release of PrecannonWarn app'
    assets: '$(Build.ArtifactStagingDirectory)/app/*.zip'
    addChangeLog: false
